### ISSUE TITLE
"PageExtension" module views/partials no longer appearing in AsgardCMS v3.

### ISSUE THREAD

**Issue by pavsid** [AsgardCms/Platform#546] opened 2018-05-31 16:58 UTC
I suspect this is to do with the new way the Page Module uses Vue.js, but without any documentation or guides we are totally stuck!

@nWidart - Any chance of a quick tutorial or at least pointing us in the right direction please? I know others are wondering how to get this working too.

Many thanks.

**Comment by sampniels** [comment] 2018-06-02 12:37
Yeap, I'm stuck on the same issue.
https://www.youtube.com/watch?v=HpzYIWOdzv8 -> this tutorial doesn't seem to work anymore, I've followed every step carefully and yet when I'm at the point where the fields should show up in the page edit in the backend, there's nothing there.

**Comment by pavsid** [comment] 2018-06-02 12:42
@sampniels Yeah that video is for version 2, can't find anything for version 3

**Comment by sampniels** [comment] 2018-06-02 13:00
Yeap, kinda sucks cause in v3 documentation https://asgardcms.com/docs/v3/workshop-module/module-scaffold it refers to a quickcast video but the video doesn't exist anymore..

**Comment by nWidart** [comment] 2018-06-04 07:49
Hello,

You're correct, this feature has been removed in version 3 because of vuejs.

The way to overwrite/extend the page module now is to remove the page module as composer dependency and commit it.

You're right the documentation should be updated.

**Comment by pavsid** [comment] 2018-06-04 11:49
@nWidart thanks for confirming.

**Comment by sampniels** [comment] 2018-06-04 19:48
@nWidart "The way to overwrite/extend the page module now is to remove the page module as composer dependency and commit it."

I'm not entirely sure what you mean by that, I've almost 0 experience with working with this CMS, got alot of experience working with Laravel though so if you could give me some global steps of what to do in order to extend the page, you'd help me out alot :)

**Comment by nWidart** [comment] 2018-06-04 19:51
Sure, though this has nothing to do with the cms or laravel but basic composer and git usage.

- start by making sure the page module is committed
- remove the page module from the main composer.json file / or run composer remove on the page module
- page module will be removed but you can add it back with git

or a simpler approach, copy the page module folder before running the composer remove command and put it back afterwards.

**Comment by pavsid** [comment] 2018-06-08 11:38
@nWidart - can we have some more guidance please? I have tried editing the Page module partials, and the `.vue` files in `\Modules\Page\Assets\js\components`, and then run `npm run prod` on the `Adminlte` theme, but still no changes are appearing. I have cleared cache & views. Thanks

**Comment by nWidart** [comment] 2018-06-08 11:55
run `npm run dev/prod` in the root of the project, not adminlte theme

**Comment by pavsid** [comment] 2018-06-08 12:03
Ah, yes that's worked, thanks. Just one more question - is there any point to the views in `\Modules\Page\Resources\views`? Seems to me that only the Vue files are used. I'm completely new to Vue so maybe misunderstanding how it works.

**Comment by nWidart** [comment] 2018-06-08 12:04
Yes, for now they're there so when you refresh a page route, it works.

**Comment by pavsid** [comment] 2018-06-08 12:09
When would we refresh a page route? I'm wondering if I need to bother changing those files also. For now I'm only adding some page attributes/extensions to the page module.

**Comment by nWidart** [comment] 2018-06-08 12:09
When you press cmd+r / f5 on a page route.

**Comment by pavsid** [comment] 2018-06-08 16:08
@nWidart - appreciate the work you've done, but this is now way too complex to customise, especially without documentation. Perhaps a feature like page attributes should be bundled out of the box, as I'm guessing the majority of users will need that functionality.

**Comment by nWidart** [comment] 2018-06-08 16:11
I see. Well it might look complex, it may be because you're not used to vuejs. Once you get the hang of it it's not as complex as it may seem.

**Comment by pavsid** [comment] 2018-06-08 16:23
Yeh that probably has a lot to do with it. However, I have got my custom fields appearing so the Vue stuff is out the way mostly. But then I hit a few other issues - `$pageId` is no longer present on the Page events, also I have no idea how to get the data _into_ the Vue template, as it seems the Composer needs refactoring also i.e. `PageAttributesComposer`.

**Comment by nWidart** [comment] 2018-10-07 15:43
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Closed by nWidart** 2018-10-07 15:43 UTC

**Comment by jmazurpl** [comment] 2019-03-16 23:28
@nWidart if old views still exists and are working is there any way to disable the vue version and use the “old one”? I’m experiencing some issues with ckeditor not loading its content and I think it might be caused by vue.
