### ISSUE TITLE
Cannot generate API key for newly created user

### ISSUE THREAD

**Issue by zsoltgyure** [AsgardCms/Platform#496] opened 2018-03-18 14:50 UTC
Api key generation throws error, so I can't use media library with a new user. Actually it does not throw any error - just an empty response with error code 500.

### Steps to reproduce
Create a user from the admin panel.
Log in with the new user and try to generate API key.

### System Details
- OS
Windows 10 x64
- PHP Version
7.1
- Laravel Version
5.5
- `Asgardcms/Platform` version
3.5.2

**Comment by nWidart** [comment] 2018-05-06 12:15
I wasn't able to reproduce this.
I added a test for this method, and passes: https://github.com/AsgardCms/Platform/commit/96c41529fb1a489706b10e53262d44b52c1e42a9

**Comment by bl3** [comment] 2018-07-09 21:14
I had the same issue, but only because i didn't configure the email settings in .env file. 
In this case the welcome email can't be sen't and no api key will be created.

**Comment by karneaud** [comment] 2018-08-08 18:08
+1 for this issue using AsgardCMS 3.x

**Comment by nWidart** [comment] 2018-10-07 15:38
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Closed by nWidart** 2018-10-07 15:38 UTC
