### ISSUE TITLE
Asgardcms is't showing font-awesome icons.

### ISSUE THREAD

**Issue by AgustinJimenez** [AsgardCms/Platform#492] opened 2018-03-11 20:30 UTC
### Summary of issue
asgardcms is't showing font-awesome icons, browser console show me this.
--Failed to decode downloaded font: 
 http://192.168.0.8:8000/themes/adminlte/vendor/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0
http://192.168.0.8:8000/themes/adminlte/vendor/font-awesome/fonts/fontawesome-webfont.woff?v=4.7.0
http://192.168.0.8:8000/themes/adminlte/vendor/font-awesome/fonts/fontawesome-webfont.ttf?v=4.7.0
OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
OTS parsing error: incorrect file size in WOFF header
OTS parsing error: FFTM: table overruns end of file

### Steps to reproduce
create new asgardcms proyect following default installations steps
https://asgardcms.com/docs/v3/getting-started/installation 

### System Details

- Operating System: Ubuntu 16.04 LTS
- PHP Version: php 7.1
- Laravel Version: default asgardcms version (5.5)
- `Asgardcms/Platform` version: current version (v3)

**Comment by nWidart** [comment] 2018-03-11 20:31
Hello,

This is a duplicate of : https://github.com/AsgardCms/Platform/issues/434

Closing this one. there are fixes explained in that issue.

**Closed by nWidart** 2018-03-11 20:31 UTC
