### ISSUE TITLE
Problem on VPS and shared hosting

### ISSUE THREAD

**Issue by szymsza** [AsgardCms/Platform#442] opened 2017-12-09 11:14 UTC
### Summary of issue
AsgardCMS doesn't work neither on shared hosting, nor on VPS. When I add .htaccess like this which should work to replace `php artisan serve` command...
`RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /server.php?path=$1 [NC,L,QSA]`
...frontend works just fine and so does most of backend. But FontAwesome doesn't load and modules, which use AJAX (e. g. Page module) just get stuck loading and 403 error is thrown in console.

### Steps to reproduce
Run AsgardCMS under Apache and add .htaccess above to root folder, then approach /backend.

### System Details

- Operating System - Windows 10 and Linux Debian
- PHP Version - 7.0 and 7.1
- Laravel Version - 5.5.*
- `Asgardcms/Platform` version - 3. 2. 1

**Comment by nWidart** [comment] 2017-12-09 13:07
It does work, I'm using it on production on vps's

**Comment by szymsza** [comment] 2017-12-09 17:49
And coul you try to solve this issue with me? What steps did you take to change dev version into prod version? Because I can't run it on hosting, VPS nor locally with EasyPHP.
Just in case, you can try my test version [here](http://cms.dkhost.cz/en/auth/login), credentials are **jakub@szymsza.cz** _testovaci1234_
Thanks a lot.

**Comment by nWidart** [comment] 2017-12-09 18:07
I can't help you without any errors. The page you linked is a 404.
I'll close this as it could be a duplicate of https://github.com/AsgardCms/Platform/issues/429

**Closed by nWidart** 2017-12-09 18:07 UTC

**Comment by szymsza** [comment] 2017-12-10 10:18
Ok so what I found out is that it's probably some problem with server settings, specifically authentification. If I remove all API middlewares, the modules that were getting 403 before suddenly work. So there must be some problem with API authentification.
This is strange however, because if I serve the exactly same files with `php artisan serve` everything works just fine.
I was trying to compare info from debug bars from working and non-working pages and all I found were differences between `$_SERVER` value in **Request** tab.  Non-working (VPS) page had many more values in the variable, but was lacking **PATH_INFO** and had some differences that may cause troubles (e. g. working version had **DOCUMENT_ROOT** with _/public_ folder while non-working didn't have public folder inlcuded in the variable).
Do you think you could try to look at this once again and try to find the bug here?
