### ISSUE TITLE
Getting error when creating a new page and link with Menu Item

### ISSUE THREAD

**Issue by kashifullahwebdeveloper** [AsgardCms/Platform#366] opened 2017-08-23 07:18 UTC
Hi @nWidart,
I am getting a strange error when creating a new menu item and link with a page slug.

Following are steps:

- First I create a page, let's say. "test" with slug "test".
- Then I go to Menu module in backend and create a new menu item, named, 'test-link' with linktype of Internal and enter the "slug" in uri.
- After that when I visit that page, I get 404 error message.

Could you please guide me what I am doing wrong?

**Comment by nWidart** [comment] 2017-08-23 07:20
Hi,

To link to a page you need to use the "page" link type. This will use the page's slug directly.

**Comment by kashifullahwebdeveloper** [comment] 2017-08-23 07:33
Thank you so much @nWidart .

Sorry I forgot to mention that step, yes, I have selected "page" link type to Internal, but still have the same issue.

**Comment by nWidart** [comment] 2017-08-23 07:35
I'm not able to reproduce this locally. Things to consider:

- Make sure your page is online
- Make sure your menu is online
- Make sure your menu item is online

**Comment by kashifullahwebdeveloper** [comment] 2017-08-23 07:36
I have seen in database table, "menu__menuitems", and found that **page_id** value get "NULL", but If I manually change that to page_id value then I am able to view the page.

**Comment by kashifullahwebdeveloper** [comment] 2017-08-23 07:40
Yes, I reassure and found that:

- Make sure your page is online (There is no such option of page is online)
- Make sure your menu is online (Yes)
- Make sure your menu item is online (Yes)

**Comment by nWidart** [comment] 2017-08-23 07:43
Ah yes, I was confusing another module with page online thing.

The menu doesn't have anything to do with the URI actually, so make sure you're accessing the correct URI set in the page, that can be the only reason you're having a 404.

**Comment by kashifullahwebdeveloper** [comment] 2017-08-23 07:50
I think that is a stupid question, but could you tell me what is the difference between **Internal** and **page** in page link type?

Yes, I have correctly given the slug of page in **uri** when "Internal" is selected in Page link type.

**Comment by nWidart** [comment] 2017-08-23 07:51
If my memory is correct, internet lets you set the URI, for instance to a custom module.

Again though, the menu module doesn't change your page uri. So you need to access the uri you set in the page.

**Comment by kashifullahwebdeveloper** [comment] 2017-08-23 07:54
I think it's a little confusing, since **Asgard** named it _slug_ in page and in Menu item it's called URI, Is that right?

**Comment by nWidart** [comment] 2017-08-23 07:54
There is no uri input in the menu item if you select the page type.

**Comment by kashifullahwebdeveloper** [comment] 2017-08-23 07:56
Correct me if I am wrong, but it's there?
![menu link](https://user-images.githubusercontent.com/12660951/29604927-7b022346-8802-11e7-81c7-03747c7fde83.png)

I have selected, Internal in Page Link Type so I have been given the URI input!

**Comment by nWidart** [comment] 2017-08-23 07:57
Exactly, I said there is none with PAGE type. You did not select page type.

**Comment by kashifullahwebdeveloper** [comment] 2017-08-23 07:59
Yes, found that issue after selecting **page** in Page link type and then selecting the page from the dropdown below solve the issue, when I am still confused what's **Internal** Page link for? Sorry my understanding.

**Comment by nWidart** [comment] 2017-08-23 08:01
internal lets you set the URI, for instance to a custom module. Asgard doesn't know about your modules uri's, that's why that's there.

I'll close this for now as I don't see any issue.

**Closed by nWidart** 2017-08-23 08:01 UTC

**Comment by kashifullahwebdeveloper** [comment] 2017-08-23 08:03
Perfect, Thank you so much @nWidart. You are the legend. 👍
