### ISSUE TITLE
[dev-2.0.x] Can't login after setup

### ISSUE THREAD

**Issue by amenk** [AsgardCms/Platform#255] opened 2016-09-18 19:30 UTC
### Summary of issue
In current dev branch: 
Can't login after setup - shows "Account not yet validated. Please check your email."
### Steps to reproduce

`php artisan asgard:install`
...
enter user email: dev@example.com
password: dev

try to login in the backend -> error

Expected:
* I can login without verification

### System Details

- Operating System: Ubuntu 16.04
- PHP Version: 7.0
- `Asgardcms/Platform`: 2.0-dev

**Comment by mikemand** [comment] 2016-09-18 20:25
There is a regression here: https://github.com/AsgardCms/Platform/pull/251/files#diff-adef50d4f5e16633aaec8a2f83fbe8baR86

I will fix and send a new PR to fix it. Thank you for reporting.

**Comment by mikemand** [comment] 2016-09-18 22:32
Should be fixed in #256.

**Comment by baotao2006** [comment] 2016-09-21 01:24
or 
$user = $this->create((array) $data, $activated);

**Comment by nWidart** [comment] 2016-09-21 06:37
No because that method explicitly don't want to send emails.

**Comment by nWidart** [comment] 2016-10-02 07:07
This was fixed in a later release.

**Closed by nWidart** 2016-10-02 07:07 UTC
