### ISSUE TITLE
New module menu entry missing

### ISSUE THREAD

**Issue by mlekoo** [AsgardCms/Platform#223] opened 2016-07-25 22:50 UTC
Hey,

### Summary of issue

I'm having a little issue with creating new module. I've followed the instructions and I created a new module using **php artisan asgard:module:scaffold** command but after that I can't see new entry in backend. I tried to clear cache, I've also noticed that there was missing code in permissions.php but I filled it as well. Of course I've checked also the Roles->Permissions settings but still can't see any new entry in menu. The **php artisan asgard:module:scaffold** operation was also successful.

### Steps to reproduce

Creating new module using **php artisan asgard:module:scaffold** on clean AsgardCMS 2 installation.

### System Details

- Operating System OSX El Capitan
- PHP Version 5.6.23
- Laravel Version 5.2
- `Asgardcms/Platform` version 2.0

Regards,
Milosz

**Comment by nWidart** [comment] 2016-07-27 13:30
Hi,

I'm unable to reproduce this here.

What data did you use to scaffold your module ?

Did you give yourself the required permissions to view the module ?

Was the module generated, if so, open the sidebar class and see what permissions are required to view it, try to remove the permission requirement.

**Comment by mlekoo** [comment] 2016-07-27 13:38
I provided module name and I chose Eloquent. After closer look I can see that there is plenty of code missing in module's files - for example in permissions.php there was missing code and I was unable to set required permissions to view the module. After providing the required code I gave myself permissions, but still couldn't see the module in menu so i took a look to another files and there wasn't also code responsible for displaying the module in sidebar, etc. It looks like the scaffold didn't generate required code but I don't have any idea why, because the process was successful and without errors. In addition I can say that every other part of CMS is working properly and the only issue I had so far is that one with creating my module.

**Comment by nWidart** [comment] 2016-07-27 13:39
What vendor / module name did you use ?

**Comment by mlekoo** [comment] 2016-07-27 13:43
To be specific used asgardcms/news

2016-07-27 15:39 GMT+02:00 Nicolas Widart <notifications@github.com>:

**Comment by nWidart** [comment] 2016-07-27 13:51
![37e3ba7f5a95080a1b763cf3f1900340](https://cloud.githubusercontent.com/assets/882397/17177482/e8da44b4-5411-11e6-883c-3d98a55f5560.png)

This is working fine.

Can you try updating composer and try again.

**Comment by armababy** [comment] 2016-07-27 13:55
Also please provide output of `composer show asgard*` if you can.

**Comment by mlekoo** [comment] 2016-07-27 18:53
```
asgardcms/adminlte-theme     1.15.1 An AsgardCMS administration theme
asgardcms/blog-module        1.15.0 A blog module for AsgardCMS.
asgardcms/core-module        1.24.3 The core module for AsgardCMS. This is ...
asgardcms/dashboard-module   1.10.0 Dashboard module for AsgardCMS. Handles...
asgardcms/flatly-theme       1.2.0  An AsgardCMS Flatly bootswatch theme
asgardcms/media-module       1.25.7 Media module for AsgardCMS. Handles the...
asgardcms/menu-module        1.17.0 Menu module for AsgardCMS. Handles all ...
asgardcms/page-module        1.15.1 Page module for AsgardCMS. Page managem...
asgardcms/setting-module     1.14.0 Setting module for AsgardCMS. Handles a...
asgardcms/translation-module 1.13.0 Module containing all AsgardCms transla...
asgardcms/user-module        1.18.0 User module for AsgardCMS. Handles the ...
asgardcms/workshop-module    1.16.0 Workshop module for AsgardCMS. Handles ...

```

**Comment by armababy** [comment] 2016-07-28 06:53
Ty, so you have AsgardCMS v1 installed.
I have tried to break scaffold, but i was not able to.

Is there any specific to your development environment? For now it's the only thing that comes in mind.

**Comment by mlekoo** [comment] 2016-07-28 07:27
Oh, yes it's v1 - I'm sorry for confusion. When it comes to development environment I've just installed all required extensions listed on AsgardCMS website.

**Comment by armababy** [comment] 2016-07-28 07:31
What do you use to host your projects on?
Like vagrant, homestead, mamp, custom stuff.

**Comment by mlekoo** [comment] 2016-07-28 08:20
Right now (in this test project) I use PHP's built-in development server.
If you think that's the problem I can move the project and see the results,
but as I said everything in this installation is working properly except
this module creation.

**Comment by armababy** [comment] 2016-07-28 08:45
Just want to boil down to any variables involved to try and duplicate this.
So far i was not able to do it.

**Comment by mlekoo** [comment] 2016-07-28 09:07
That's kind of weird, because I can see that the files are present in News
directory, but when I look at the content of those files it seems to be
incomplete (some code, e.g. to display it in menu). Of course I can fill
all those files manually and then it's working properly, but still it would
be nicer to use generator.

**Comment by nWidart** [comment] 2016-07-28 09:10
From the output you're describing it looks like you ran `module:make` command, since that's the command that generates the base module, and asgard afterwards adds additional classes.

**Comment by mlekoo** [comment] 2016-07-28 09:23
I'm sure I used *php artisan asgard:module:scaffold* and more than one
time, because I thought that maybe I've just done something wrong, so I
tried to create another module. Maybe I'll just try with another
environment - If you can't reproduce my issue, then most probably it has
something to do with my environment.

**Comment by nWidart** [comment] 2016-08-18 06:47
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Closed by nWidart** 2016-08-18 06:47 UTC

**Comment by namitasurve177** [comment] 2017-10-23 10:05
im also getting same issues.when i created new custom module projects its not visible in admin panel and rest migrations files too missing.whether module not successfully not created or is there something else i need to do
