### ISSUE TITLE
Thumbnails not being generated

### ISSUE THREAD

**Issue by OrchardMarketings** [AsgardCms/Platform#320] opened 2017-04-28 00:16 UTC
### Summary of issue
When i upload an image in media module it's not creating the thumbnails, this is very similar to what was raised https://github.com/AsgardCms/Platform/issues/291 but can't replicate the solution

### Further descriptions
1. Image is being successfully uploaded and saved within the public folder
2. No PHP error logs
3. No log file within storage folder
4. GD lib is installed and jpeg, png is enabled (see attached screenshot)
5. Media/Config/thumbnails.php 
```return [
    'smallThumb' => [
        'resize' => [
            'width' => 50,
            'height' => null,
            'callback' => function ($constraint) {
                $constraint->aspectRatio();
                $constraint->upsize();
            },
        ],
    ],
    'mediumThumb' => [
        'resize' => [
            'width' => 180,
            'height' => null,
            'callback' => function ($constraint) {
                $constraint->aspectRatio();
                $constraint->upsize();
            },
        ],
    ],
];
```
7. Running `php artisan asgard:media:refresh` doesn't regenerate thumbnails although terminal console shows `Preparing to regenerate all thumbnails...` and `All thumbnails refreshed` 

### Steps to reproduce
1. Upload an image < 

### System Details

- Operating System Windows (Local), Ubuntu (Staging)
- PHP Version 5.6
- Laravel Version 5.1.45
- `Asgardcms/Platform` version 1.14

![gd-lib](https://cloud.githubusercontent.com/assets/26951818/25509131/12652d88-2bfa-11e7-9938-70cd1b026eb7.JPG)

**Comment by jdnierth** [comment] 2017-04-28 14:23
Closing this ticket as it is not a bug. AsgardCMS/Media module (used version 1.25.2) generates the thumbnails fine. The issue was that the Thumbnail generation task was deferred by a queue.

**Closed** 2017-04-28 14:25 UTC
