### ISSUE TITLE
Page module admin page is not working if hideDefaultLocaleInURL option is used

### ISSUE THREAD

**Issue by VasiliDarozhkin** [AsgardCms/Platform#386] opened 2017-09-27 22:20 UTC
### Summary of issue
If I want to get rid of language in the URL, admin page of `Page` module is not working

### Steps to reproduce
* Install fresh AsgardCMS
* check if pages list is available (using `/en/backend/page/pages`)
* set `hideDefaultLocaleInURL' => true` in `config/laravellocalization.php`
* The pages list is not displayed

### System Details

- Operating System: Homestead instance
- PHP Version: 7.1
- Laravel Version 5.5
- `Asgardcms/Platform` version: 3.0.2

**Comment by nWidart** [comment] 2017-09-28 06:37
Hello,

Thanks for reporting the issue. It has been fixed and will be tagged for `3.1` releasing soon.

**Comment by nWidart** [comment] 2017-09-28 10:24
Hm that's odd, I can't reproduce this locally.

I changed `backend` to cms, and the pages are still accessible via `/cms/page/pages`.

The fix for the locale itself is easy, but will require you to compile app.js:

https://github.com/AsgardCms/Platform/blob/80f0bd67c2669cde1274c196bfdc4f4c75b37a43/resources/assets/js/app.js#L43-L48

**Comment by MikeZange** [comment] 2017-09-28 14:04
Hey,

I will implement the fix above but i feel like it won't fix the issue.

Tried this on a fresh install of Asgard 3.0.3 after running asgard:install, the only change was the admin-prefix.

Screen shots of issue:
Backend:
![backend](https://user-images.githubusercontent.com/5443707/30970779-f1f6c8a4-a45d-11e7-9a73-e638f7c74542.png)

CMS:
![cms](https://user-images.githubusercontent.com/5443707/30970860-2c331464-a45e-11e7-87cb-8bf4750097a7.png)

**Comment by nWidart** [comment] 2017-09-28 14:06
![image](https://user-images.githubusercontent.com/882397/30970985-fc7ca86c-a466-11e7-8b22-fb53570e42d3.png)

And I have a screenshot if the prefix working.

**Comment by MikeZange** [comment] 2017-09-28 14:09
Hmm, haha, I will try to narrow it down and come back if i find anything.

Thanks for looking 👍

**Comment by nWidart** [comment] 2017-09-28 14:10
It's probably related to a difference in [app.js](https://github.com/AsgardCms/Platform/blob/3.0/resources/assets/js/app.js).

**Comment by MikeZange** [comment] 2017-09-28 14:16
You are right, in that file I seem to have this:

`const router = new VueRouter({
    mode: 'history',
    base: `${currentLocale}/backend`,
    routes : [
        ...PageRoutes,
    ],
});`

**Comment by joshbrw** [comment] 2017-09-28 14:19
Could this be solved by a new property on the `window` object that states the base url for the cms?

**Comment by nWidart** [comment] 2017-09-28 14:20
Indeed @joshbrw that and you need to use the new function mentioned above.

```js
const router = new VueRouter({
    mode: 'history',
    base: makeBaseUrl(),
    routes : [
        ...PageRoutes,
        ...MediaRoutes,
    ],
});
```

**Closed** 2017-09-28 19:24 UTC

**Comment by Jaylaxmiaussizz** [comment] 2019-03-14 07:26
I tried with above options but Page Module and some other modules are showing me blank page in admin. and even frontend side no css or content display.

**Comment by ewsdevteam** [comment] 2021-07-07 11:19
Hi I am using Asgard for my project I have configured it on localhost it works well but when I have uploaded my project on server the page module in admin panel is not working showing blank page please help its urgent
