### ISSUE TITLE
Error on edit page

### ISSUE THREAD

**Issue by wassimhattab** [AsgardCms/Platform#227] opened 2016-08-08 13:33 UTC
### Summary of issue
I created a new module 'contact' with two entities 'content' and 'messages',
and i modified the create and edit blade and the entities but i'm facing a problem in edit page of contact content it's not getting data on edit page, i noticed in the query that it's trying to get data from home__content instead of contact_content

![untitled](https://cloud.githubusercontent.com/assets/20112008/17481390/a5afa8aa-5d85-11e6-9e6f-57e234d36bfe.jpg)

any solution?

### System Details

- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` version

**Comment by armababy** [comment] 2016-08-08 15:18
If it's not a bug, then it looks like you replaced or generated module with name `home`.
Anyway you can go and change `home__` in Entities, Migrations, Seeders to `contact__`

**Comment by wassimhattab** [comment] 2016-08-09 07:38
It's because i have two content entities in two different module i have content in home and content in contact

**Comment by nWidart** [comment] 2016-08-09 07:41
This means you have a home module ?

If it's not getting your entity on the edit view, you can check your route model binding in the routes files.
Make sure the route parameter matches the one used in the binding. Make sure also that the route parameter name is unique.

**Comment by wassimhattab** [comment] 2016-08-09 07:44
I have home module and contact module and in each one of them i have content

**Comment by nWidart** [comment] 2016-08-09 07:44
Please read my answer above. It's most likely an issue on the route model binding.

**Comment by nWidart** [comment] 2016-08-09 07:45
And a quick search on the forum shows this: http://forum.asgardcms.com/topic/98/module-s-edit-view-does-not-display-data/6

**Comment by nWidart** [comment] 2016-08-18 06:46
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Closed by nWidart** 2016-08-18 06:46 UTC
