### ISSUE TITLE
No query results for model [Modules\Menu\Entities\Menuitem]

### ISSUE THREAD

**Issue by rockymontana** [AsgardCms/Platform#198] opened 2016-05-18 08:10 UTC
Next Issue
### Summary of issue

![image](https://cloud.githubusercontent.com/assets/330839/15351416/7e8973f0-1cdf-11e6-9920-b81d42405e67.png)
**fig. 1**

![image](https://cloud.githubusercontent.com/assets/330839/15351681/bf50db2a-1ce0-11e6-8da8-41116ef96642.png)
**fig. 2**

### Steps to reproduce
fig. 1: 

- Go to Menus and create a new Menu. When saving I get the error above.
- When going back to the menus I see the menu in the item list. So creating the menu itself works just fine, however that is a really annoying message.

fig. 2: 
- I tried to add a page that I created (thanks for the help with that oh btw). When adding a page 
- Same as for fig. 1... The link item get added to the menu item. But I still receive an error message in the saved-event that's being triggered.

Is it still me being silly? ^o^

### System Details

OS X - El Capitan
7.0.6
Laravel Framework version 5.1.35 (LTS)
```
  "require": {
    "laravel/framework": "~5.1",
    "pingpong/modules": "dev-feature/5.1",
    "cartalyst/sentinel": "~2.0",
    "asgardcms/core-module": "~1.0",
    "asgardcms/dashboard-module": "~1.0",
    "asgardcms/user-module": "~1.0",
    "asgardcms/setting-module": "~1.0",
    "asgardcms/media-module": "~1.0",
    "asgardcms/page-module": "~1.0",
    "asgardcms/menu-module": "~1.0",
    "asgardcms/workshop-module": "~1.0",
    "asgardcms/translation-module": "~1.0",
    "asgardcms/flatly-theme": "~1.0",
    "asgardcms/adminlte-theme": "~1.0",
    "asgardcms/notification-module": "^1.3"
  },```

**Comment by nWidart** [comment] 2016-05-18 08:15
I could not reproduce any of the 2 issues following the steps.

Blind guess would be to make sure you are on the latest versions.

**Comment by rockymontana** [comment] 2016-05-18 08:16
Is there any way to determine what versions my modules and asgardCMS is running via - say - artisan?

**Comment by armababy** [comment] 2016-05-18 08:21
@rockymontana should be something like ``composer show asgard*`` for that, also ``composer outdated asgard*`` is a nice one sometimes if you want to see if any upgrade is available.

**Comment by rockymontana** [comment] 2016-05-18 08:24
```
 "name": "asgardcms/core-module",
            "version": "1.24.1",
"name": "asgardcms/menu-module",
            "version": "1.16.0",
"name": "asgardcms/dashboard-module",
            "version": "1.9.0",
"name": "asgardcms/flatly-theme",
            "version": "1.2.0",
"name": "asgardcms/media-module",
            "version": "1.21.0",
```

I'm at the latest on everything - and - on a clean install 😭

**Comment by rockymontana** [comment] 2016-05-18 08:27
@armababy the wildcard trick didn't work on latest composer update - FYI

**Comment by rockymontana** [comment] 2016-05-18 08:36
@armababy `Composer version 1.1.1 2016-05-17 12:25:44`

Buuut - getting quite far OT now...

**Comment by armababy** [comment] 2016-05-18 08:41
@rockymontana right, so what locales enabled in the settings page? I'll also try to poke this one.

**Comment by rockymontana** [comment] 2016-05-18 08:44
None atm. English seems to be fallback according to the admin-URL, is that so?

**Comment by armababy** [comment] 2016-05-18 08:55
Yeah should be fallback. Hmm, i can't quite break that foreach it works for me as expected.

**Comment by rockymontana** [comment] 2016-05-18 09:01
I'll xdebug it and see what I can come up with.

**Comment by nWidart** [comment] 2016-07-04 10:56
I'll close this for the time being as we weren't able to reproduce the issue.

**Closed** 2016-07-15 06:43 UTC
