### ISSUE TITLE
When I create a new user, login with the user just created in the media does not work

### ISSUE THREAD

**Issue by linhtinh92** [AsgardCms/Platform#335] opened 2017-06-27 22:45 UTC

**Comment by nWidart** [comment] 2017-06-28 08:23
I can't reproduce this locally.

What do you mean by media does not work? Make sure you have the appropriate permissions on disk.

**Comment by motchju** [comment] 2017-06-28 09:05
I believe you have to create an API Keys for the new user

**Comment by linhtinh92** [comment] 2017-06-28 09:06
https://www.screencast.com/t/OZIl3oRjo

this is video.

**Comment by nWidart** [comment] 2017-06-28 09:17
The video required flash 😂 .

**Comment by motchju** [comment] 2017-06-28 09:18
anyway it's a forbidden, due to lack of API key

**Comment by nWidart** [comment] 2017-06-28 09:54
I see. This was fixed on the 2.0 branch if you want to use this currently.

**Comment by linhtinh92** [comment] 2017-06-28 09:57
thanks all 👍

**Closed** 2017-06-28 10:12 UTC
