### ISSUE TITLE
Unable to create new roles

### ISSUE THREAD

**Issue by tanthammar** [AsgardCms/Platform#623] opened 2018-10-10 16:54 UTC
### Summary of issue
Unable to create new Role. Get "the spinning wheel"
No errors in laravel debug bar, but vue error:
/en/api/user/roles/find-new:1 Failed to load resource: the server responded with a status of 500 ()

### Steps to reproduce
en/backend/user/roles/create + "New Role"

### System Details
fresh install
- Operating System osx 10.13.6
- PHP Version 7.2
- Laravel Version 5.7
- `Asgardcms/Platform` version 4.0.x-dev

**Comment by mikemand** [comment] 2018-10-10 21:51
Looks like this is caused by this:

https://github.com/AsgardCms/Platform/blob/1604c2555908e06c7a5f18f63746a82fc49e7576/Modules/User/Transformers/FullRoleTransformer.php#L22-L24

It was fixed in `FullUserTransformer`, but not `FullRoleTransformer`. PR incoming. 😃

**Closed** 2018-10-16 09:17 UTC
