### ISSUE TITLE
Error in translation revision after editing value

### ISSUE THREAD

**Issue by MehediDracula** [AsgardCms/Platform#308] opened 2017-01-25 17:40 UTC
### Summary of issue
After editing a translation value revising modal is not showing. 

The ajax request is getting a 500 error.

![screenshot_1](https://cloud.githubusercontent.com/assets/10138936/22302091/8c637270-e357-11e6-8ecf-b3726dd66d89.png)

### Steps to reproduce
Edit a translation value on **/translation/translations**
Click on revision button

### System Details

- Operating System: Windows
- PHP Version: 5.6.23
- Laravel Version: 5.3.19
- `Asgardcms/Platform` version: 2

**Comment by nWidart** [comment] 2017-06-29 14:33
Nevermind, could just reproduce this on a field that has multiple translations. Happens because the user_id column is `null`. Looking into it.

**Comment by nWidart** [comment] 2017-06-29 14:49
This was just fixed in latest version.

Sorry for the late reply! 😄

**Closed** 2017-06-29 14:49 UTC
