### ISSUE TITLE
Sidebar title translation error when scaffolding a module

### ISSUE THREAD

**Issue by gverschuur** [AsgardCms/Platform#90] opened 2015-07-29 08:57 UTC
Using Asgard 1.2.2 (installed using composer create-project), when scaffolding a module I encountered an error that the backend sidebar title could not be translated. 

I created a new module `News` with one Eloquent entity also named `News`. In the generated `SidebarExtender.php` however, the group item was looking for `news::abcs.title.abcs` for the translation key.

I have no idea where the *abcs* came from, but I'm pretty sure I didn't type that during the scaffolding process. :)

**Comment by nWidart** [comment] 2015-07-29 09:39
It looks like you have called your entity `abcs`.

This is the stub that's being used: https://github.com/AsgardCms/Workshop/blob/develop/Scaffold/Module/stubs/sidebar-extender.stub#L33

**Comment by gverschuur** [comment] 2015-07-29 10:04
No, that's the thing, I give the entity the name `News`. Here is what I did 

	php artisan asgard:module:scaffold 

	Please enter the module name in the following format: vendor/name > myproject/news

	Eloquent or Doctrine > blank

	Enter entity name (first time) > News

	Enter entity name (second time) > blank

	Enter value object name > blank

	Module generated and is ready to be used.

The path of the entity is `Modules/News/Entities/News.php`, the class definition is `class News extends Model`. Nowhere in the module folder is there a reference for __abcs__.

**Comment by nWidart** [comment] 2015-07-29 10:15
So managed to reproduce the error. And it's related to laravel, when it can't find a plural, it returns `abcs`.

When creating a `recipe` entity, it used `recipes`.

**Comment by nWidart** [comment] 2015-07-29 11:11
I'll close this since it's sadly not something we can fix here. An issue/PR may be submitted on the laravel or symfony repositories.

Thank you for reporting the issue! :smile:

**Closed by nWidart** 2015-07-29 11:11 UTC

**Comment by gverschuur** [comment] 2015-07-29 11:13
I agree, this is outside the scope of this project. Will check it out in the code and report it to the Laravel team.

**Comment by nmpribeiro** [comment] 2015-08-21 06:36
Go to yourModule/Sidebar/SidebarExtender.php and change trans('yourmodule ::abcs.title.abcs') to trans('yourmodule ::menu.title'), go to Resources/lang/en create a 'menu.php' file and add 
```
<?php

return [
    'title' => 'yourmodule title',
];
```
Now you have it and know how to create translatable items. 

The default absc.title.abcs expects some imput in file absc.php that has sort of this content:
<?php

return [
    'title' => [
          'abcs' => 'yourmodule title',
    ],
];
```
So... yourmodule::[filename].[key].[value]

**Comment by ali-hellani** [comment] 2016-01-14 09:32
Hello @nWidart

i was trying to scaffold the same module as you did in your tutorial (Testimonials), but i encountered the same error ```testimonials::abcs.title.abcs``` on the backend sidebar title.

when i have replaced this ``` trans('testimonials::abcs.title.abcs' ``` in ```SidebarExtender.php``` with this ```trans('testimonials::testimonials.title.testimonials'``` ==> **it worked.**

**Note:** i have Laravel Framework version 5.1.28 (LTS)

**Comment by joshbrw** [comment] 2016-01-14 10:13
@ali-hellani Yeah, changing the key manually will work. This error is related to the pluralizer in Laravel (which runs off Doctrine's Inflector - https://github.com/doctrine/inflector/blob/master/lib/Doctrine/Common/Inflector/Inflector.php#L386)

**Comment by ali-hellani** [comment] 2016-01-14 10:30
but i have used the same word as in the video tutorial !
