### ISSUE TITLE
Error in Edit a Page 

### ISSUE THREAD

**Issue by yoelianto** [AsgardCms/Platform#412] opened 2017-10-11 22:57 UTC
### Summary of issue
There are some error when edit Page.
From Browser Console :
VM582 pages:14 The key "viewport-fit" is not recognized and ignored.
app.js:8703 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
app.js:8713 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html

VM582 pages:1 Failed to decode downloaded font: http://localhost/themes/adminlte/vendor/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0
VM582 pages:1 OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
VM582 pages:1 Failed to decode downloaded font: http://localhost/themes/adminlte/vendor/font-awesome/fonts/fontawesome-webfont.woff?v=4.7.0
VM582 pages:1 OTS parsing error: incorrect file size in WOFF header
VM582 pages:1 Failed to decode downloaded font: http://localhost/themes/adminlte/vendor/font-awesome/fonts/fontawesome-webfont.ttf?v=4.7.0
VM582 pages:1 OTS parsing error: FFTM: table overruns end of file
app.js:1188 [Vue warn]: Invalid prop: type check failed for prop "entityId". Expected Number, got Object.

found in

---> <SingleMedia> at Modules/Media/Assets/js/components/SingleMedia.vue
       <ElForm>
         <PageForm> at Modules/Page/Assets/js/components/PageForm.vue
           <Root>
warn @ app.js:1188
app.js:5688 Failed to decode downloaded font: http://localhost/themes/adminlte/vendor/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0
removeChild @ app.js:5688
app.js:5688 OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
removeChild @ app.js:5688
app.js:5688 Failed to decode downloaded font: http://localhost/themes/adminlte/vendor/font-awesome/fonts/fontawesome-webfont.woff?v=4.7.0
removeChild @ app.js:5688
app.js:5688 OTS parsing error: incorrect file size in WOFF header
removeChild @ app.js:5688
app.js:5688 Failed to decode downloaded font: http://localhost/themes/adminlte/vendor/font-awesome/fonts/fontawesome-webfont.ttf?v=4.7.0
removeChild @ app.js:5688
app.js:5688 OTS parsing error: FFTM: table overruns end of file
removeChild @ app.js:5688
app.js:1188 [Vue warn]: Invalid prop: type check failed for prop "entityId". Expected Number, got Object.
............................

**Comment by nWidart** [comment] 2017-10-12 08:04
Hello,

Those are not errors but warnings, to be expected.

- The key "viewport-fit" is not recognized and ignored. =>  normal, for the coming iphone
- vuejs dev tools => normal

**Comment by yoelianto** [comment] 2017-10-12 08:31
But loading indicator in Edit a Page always show.

**Comment by nWidart** [comment] 2017-10-12 08:31
Ah I see. there's an actual error in what you posted.

```
[Vue warn]: Invalid prop: type check failed for prop "entityId". Expected Number, got Object.
```

**Comment by nWidart** [comment] 2017-10-12 08:37
Strange, I can't reproduce this locally when creating a new page.

Did you change something on the components?

Because by default there is no way it's receiving an object:

```
<single-media zone="image" @singleFileSelected="selectSingleFile($event, 'page')"
      entity="Modules\Page\Entities\Page" :entity-id="page.id"></single-media>
```

**Comment by yoelianto** [comment] 2017-10-12 08:39
No, i didn't. it was fresh install

**Comment by nWidart** [comment] 2017-10-12 08:39
can you try to log the entityId here: https://github.com/AsgardCms/Platform/blob/3.0/Modules/Media/Assets/js/components/SingleMedia.vue#L51 and see what's returned?

**Comment by nWidart** [comment] 2017-10-12 08:45
I just installed a fresh version of asgard, went to the pages index.
I could edit the homepage, add an image, and save the page without errors.

**Comment by yoelianto** [comment] 2017-10-12 23:08
It happened when added language in Setting > Site Locales. If new language removed, it's fine

**Comment by nWidart** [comment] 2017-10-13 07:47
Hm I've added a new language in the settings. Went back to page edit, and didn't get an error.

**Comment by yoelianto** [comment] 2017-10-13 08:50
I added "Spanish" language and didn't get error, but "Indonesian", it's error. 

There are warn and error in console:

app.js:1188 [Vue warn]: Invalid prop: type check failed for prop "entityId". Expected Number, got Object.
.......................
app.js:28887 POST http://localhost-aay/en/api/page/pages/1 500 (Internal Server Error)
..................

**Comment by nWidart** [comment] 2017-10-13 10:31
Alright thank you, I could re-produce the bug and fix it.

Fix will be coming to `3.2`. However for you locally you can already try to change the key `id` to `ind` in `config/available-locales.php` file.

**Comment by arturmamedov** [comment] 2017-10-16 20:28
I receive 
```

message | SQLSTATE[23000]: Integrity con…:28:25, 2017-10-16 20:28:25))
-- | --
exception | Illuminate\Database\QueryException
file | A:\serverpath\2017\sites\Asgar…inate\Database\Connection.php
line | 664
```

**Comment by nWidart** [comment] 2017-10-16 20:56
@arturmamedov This isn't related to this issue.

That issue has been fixed on version `3.2` that should be released soon.

**Comment by arturmamedov** [comment] 2017-10-16 22:32
@nWidart and what about amyne one, in Page module the status aren't passed on save, the field arer missed in HTML view, i must create new issue?

**Comment by nWidart** [comment] 2017-10-17 07:27
Normally yes, but as I said this is fixed already.

**Comment by nWidart** [comment] 2017-10-17 17:42
This was tagged.

**Closed by nWidart** 2017-10-17 17:42 UTC
